# Generated by Django 2.2.7 on 2019-11-25 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('PlantName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('GrowthHabit', models.TextField()),
                ('Picture', models.ImageField(upload_to='PlantPic')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserNo', models.EmailField(max_length=254, unique=True)),
                ('UserName', models.CharField(max_length=15)),
                ('Password', models.SlugField(max_length=16)),
                ('Phone', models.CharField(max_length=11)),
                ('Freetimes', models.IntegerField(default=6)),
                ('Identify', models.CharField(choices=[('个人', '个人'), ('公司', '公司')], default='个人', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PlantDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiseaseName', models.CharField(max_length=15)),
                ('Morbidity', models.CharField(max_length=15)),
                ('Symptoms', models.TextField()),
                ('PreMeasures', models.TextField()),
                ('Img', models.ImageField(upload_to='img')),
                ('PlantName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantname', to='myapp.Plant')),
            ],
        ),
    ]
