# Generated by Django 2.2.7 on 2019-11-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191125_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdisease',
            name='Morbidity',
        ),
    ]
